install.packages('stats')
install.packages('readxl')
install.packages('Metrics')
library(stats)
library(readxl)
library(Metrics)
SDBdata <- read_xlsx("C:/Users/rjp14/Downloads/SDBfinal_data.xlsx")
summary(SDBdata)
missing_per_columns<-colSums(is.na(SDBdata))
print(missing_per_columns)
average_scores=(SDBdata$Math_18_19 + SDBdata$Read_18_19)/2
academic_achievement_Math<-lm(Math_18_19~Old_School_Label + Sex + Special_Ed + Disability + Fed_Race + Eng_Prof + Q1_3 + Q1_7 + Q2_1 + Q2_2 + Children_Per_Adult + Q2_3 + Q2_5 + Q3_1 + Q3_2 +Q3_4 +Q4_1 + Q4_2 + Q4_4 + Q5_1 + Q6_1 + Q6_3 + Q6_4 + Q6_5 + Q6_7 + Q6_8, data = SDBdata)
academic_achievement_Read<-lm(Read_18_19~Old_School_Label + Sex + Special_Ed + Disability + Fed_Race + Eng_Prof + Q1_3 + Q1_7 + Q2_1 + Q2_2 + Children_Per_Adult + Q2_3 + Q2_5 + Q3_1 + Q3_2 +Q3_4 +Q4_1 + Q4_2 + Q4_4 + Q5_1 + Q6_1 + Q6_3 + Q6_4 + Q6_5 + Q6_7 + Q6_8, data = SDBdata)
academic_achievement_combined<-lm(average_scores~Old_School_Label + Sex + Special_Ed + Disability + Fed_Race + Eng_Prof + Q1_3 + Q1_7 + Q2_1 + Q2_2 + Children_Per_Adult + Q2_3 + Q2_5 + Q3_1 + Q3_2 +Q3_4 +Q4_1 + Q4_2 + Q4_4 + Q5_1 + Q6_1 + Q6_3 + Q6_4 + Q6_5 + Q6_7 + Q6_8, data = SDBdata)
academic_achievement_final<-lm(average_scores~Old_School_Label + Special_Ed + Eng_Prof + Q2_3, data = SDBdata)
summary(academic_achievement_Math)
summary(academic_achievement_Read)
summary(academic_achievement_combined)
summary(academic_achievement_final)
x<-mae(average_scores, predict(academic_achievement_final))
print(x)

